'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SimpleDyno.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property AxelMass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AxelMass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AxleDiameter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AxleDiameter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CarMass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CarMass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DragImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DragImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DynoBasicImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DynoBasicImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EndCapMass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EndCapMass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ExtraDiameter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExtraDiameter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ExtraMass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExtraMass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ExtraWallThickness() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExtraWallThickness", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FrontalArea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FrontalArea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GearRatio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GearRatio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RollerDiameter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RollerDiameter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RollerMass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RollerMass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RollerWallThickness() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RollerWallThickness", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SD() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SD", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property SignalsPerRPM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignalsPerRPM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WheelDiameter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelDiameter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
